---
apiVersion: v1
kind: Namespace
metadata:
  name: minns

---
apiVersion: v1
kind: Service
metadata:
  name: min-hsvc
  labels:
    name: min-hsvc
  namespace: minns
spec:
  clusterIP: None
  selector:
    name: min-pod
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: min-sts
  labels:
    name: min-sts
  namespace: minns
spec:
  replicas: 4
  serviceName: min-hsvc
  selector:
    matchLabels:
      name: min-pod
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: min-pod
      labels:
        name: min-pod
    spec:
      initContainers:
        - name: min-init-container
          image: busybox
          command:
            - /bin/sh
            - -c
            - "chown 1001 /data"
          volumeMounts:
            - name: data-vol
              mountPath: /data
      containers:
        - name: min-container
          image: bitnami/minio
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ROOT_USER
              value: rootroot
            - name: MINIO_ROOT_PASSWORD
              value: Y2hhbmdlaXRvbWc=
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MINIO_SERVER_URL
              value: ${MY_POD_NAME}.min-hsvc.minns.svc.cluster.local
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data-vol
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
          resources:
            requests:
              cpu: 200m
              memory: 250M
---
apiVersion: v1
kind: Service
metadata:
  name: min-svc
  labels:
    name: min-svc
  namespace: minns
spec:
  type: LoadBalancer
  selector:
    name: min-pod
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: min-ing
  labels:
    name: min-ing
spec:
  ingressClassName: nginx
  rules:
    - host: min-146.190.202.84.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: min-svc
                port:
                  number: 9000
