---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovbear-deploy
  labels:
    name: dovbear-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dovbear-pod
  template:
    metadata:
      name: dovbear-pod
      labels:
        name: dovbear-pod
    spec:
      containers:
      - name: dovbear-container
        image: chukmunnlee/dov-bear-golang:0.1
        resources:
          requests:
            cpu: 100m
            memory: 16M
          limits:
            memory: 16M
        imagePullPolicy: IfNotPresent
        env:
          - name: INSTANCE_NAME
            value: dovbear1
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: '3000'
        ports:
          - containerPort: 3000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    name: dovbear-pod
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1 
kind: Service 
metadata: 
  name: dov-bear-hsvc 
  labels:
    name: dov-bear-hsvc 
  namespace: myns
spec:
  clusterIP: None
  selector: 
    name: dovbear-pod
  ports: 
  - port: 3000 
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dovbear-hpa
  labels:
    name: dovbear-hpa
  namespace: myns
spec: 
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dovbear-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 30

