---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovbear-deploy
  labels:
    name: dovbear-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dovbear-pod
  template:
    metadata:
      name: dovbear-pod
      labels:
        name: dovbear-pod
    spec:
      containers:
      - name: dovbear-container
        image: chukmunnlee/dov-bear-golang:0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: INSTANCE_NAME
            value: dovbear1
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: '3000'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    name: dovbear-pod
  ports:
  - port: 3000
    targetPort: 3000
