---
apiVersion: v1
kind: Pod
metadata:
  name: dovbear-pod
  labels:
    name: dovbear-pod
  namespace: myns
spec:
  containers:
  - name: dovbear-container
    image: chukmunnlee/dov-bear-golang:0.1
    imagePullPolicy: IfNotPresent
    env:
      - name: INSTANCE_NAME
        value: dovbear1
      - name: HEROKU_WORKAROUND
        value: 'true'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000

