---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: myns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
  storageClassName: do-block-storage-xfs
