---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: task1-app-pod
  ports:
  - port: 3000
    targetPort: 3000